#pragma once

#define BLCKR_MOUSE_BUTTON_1         0
#define BLCKR_MOUSE_BUTTON_2         1
#define BLCKR_MOUSE_BUTTON_3         2
#define BLCKR_MOUSE_BUTTON_4         3
#define BLCKR_MOUSE_BUTTON_5         4
#define BLCKR_MOUSE_BUTTON_6         5
#define BLCKR_MOUSE_BUTTON_7         6
#define BLCKR_MOUSE_BUTTON_8         7
#define BLCKR_MOUSE_BUTTON_LAST      BLCKR_MOUSE_BUTTON_8
#define BLCKR_MOUSE_BUTTON_LEFT      BLCKR_MOUSE_BUTTON_1
#define BLCKR_MOUSE_BUTTON_RIGHT     BLCKR_MOUSE_BUTTON_2
#define BLCKR_MOUSE_BUTTON_MIDDLE    BLCKR_MOUSE_BUTTON_3